services:    
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    profiles: ["full", "backend"]
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    command: pnpm dev:front
    profiles: ["full", "frontend"]