name: CI to Azure Container Registry

# ワークフローが実行されるトリガー条件。
on: workflow_dispatch

jobs:
  build:
    # 実行環境はUbuntuを指定
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      # Dockerにログインする。ビルドとプッシュ作業の前に必要
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          # ACRのドメインを指定。
          registry: buildchatest.azurecr.io
          # GitHub Secretsからユーザー名とパスワードを取得。
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # ここでDockerイメージのビルドとACRへのプッシュする。
      - name: Build and push Docker image
        run: |
          docker compose --profile frontend build
          docker compose --profile frontend push
